### ISSUE TITLE
Broken link on about page

### ISSUE THREAD

**Issue by erochest** [scholarslab/neatline.org#10]
From the mailing list:

> On this page http://neatline.org/about/  In this sentence "Through Neatline, you can create create rich representations of places, objects, events, narratives, and documents — like these demo exhibits.” the link "these demo exhibits.” give you a 404 error message (see attached image)
> 
> Thanks,
> Rafia

**Comment by csbailey5t** [comment]
Fixed in 59aad24f87d4f6e51f1f23e310aef8c32d42fe58

**Comment by waynegraham** [comment]
Can someone make sure this got responded to on the list?

**Comment by csbailey5t** [comment]
I'll do so @waynegraham.
