### ISSUE TITLE
White line artifacts on transit image

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/neatline.org#7]
On the desktop browsers I've tried on OS X, there is a white outline on the transit in the background. This looks like an artifact of stretching the image over the entire page. May need to regenerate this from the SVG (but not use SVG so Firefox won't fall over).

**Comment by csbailey5t** [comment]
This was an issue with scaling fixed in e25ae4eb0608f5e269d2f0455f88c3a3e89471da.
