### ISSUE TITLE
Publications Section

### ISSUE THREAD

**Issue by waynegraham** [scholarslab/neatline.org#8]
I know there are some publications that are featuring Neatline. There's at least one more in the pipeline that I know of, but this one popped up. 

http://www.19thc-artworldwide.org/index.php/autumn14/musacchio-anne-whitney-abroad

We should have a section for publications on the site.

**Comment by csbailey5t** [comment]
Added and arranged in 69f966f3ddd8cbb1fac134c8452afd313ab886b3, 43601575325f73092e822cbe8d56a0acae3cb6d2, and ed981fd30c7198001bcae0844c353cf8de111543.
